#!/bin/bash

WORKSPACE=${TBC_WORKSPACE:-`pwd`:/workspace}
xhost +
docker run -ti --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v `pwd`:/workspace \
           jontutcher/docker-tbc $@
